// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import './globals.css'
import { Inter } from 'next/font/google'
// import { ThemeProvider } from '@/components/theme-provider'
import { Header } from './components/header'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MOM Generator AI',
  description: 'Generate comprehensive meeting minutes with AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
          <div className="flex flex-col min-h-screen bg-gradient-to-br from-background to-secondary">
            <div className="absolute inset-0 bg-grid-white/[0.02] bg-[size:50px_50px]" />
            <Header />
            <div className="bg-red-400 flex justify-center items-center w-full py-4">
            This App is under Development
          </div>
            <main className="flex-grow relative">
              <div className="absolute inset-0 bg-spotlight opacity-20" />
              <div className="relative z-10">
                {children}
              </div>
            </main>
        
          </div>
        {/* </ThemeProvider> */}
      </body>
    </html>
  )
}

